workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: "3.19.5" # Фиксированная версия
      xcode: latest
      cocoapods: "1.15.2" # Фиксированная версия
    scripts:
      # 1. Полная очистка
      - name: Очистка проекта
        script: |
          flutter clean
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec
          
      # 2. Принудительное создание iOS-файлов
      - name: Пересоздание iOS-проекта
        script: |
          if [ -d "ios" ]; then
            rm -rf ios
          fi
          flutter create --platforms ios --org com.yourdomain .
          
      # 3. Обновление зависимостей
      - name: Обновление зависимостей
        script: |
          flutter pub upgrade --major-versions
          cd ios
          pod repo update
          pod deintegrate || true # Игнорировать ошибки, если Pods нет
          pod install --repo-update
          
      # 4. Сборка с подробным логом
      - name: Сборка IPA
        script: |
          flutter build ipa --release --verbose
          
    artifacts:
      - build/ios/ipa/*.ipa