workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # 1. Инициализация Keychain (для подписи кода)
      - name: Set up keychain
        script: |
          keychain initialize

      # 2. Обновление Flutter и пакетов
      - name: Upgrade Flutter and fix dependencies
        script: |
          flutter upgrade
          flutter pub upgrade --major-versions
          flutter clean

      # 3. Генерация iOS-файлов (если их нет)
      - name: Generate iOS files (if missing)
        script: |
          if [ ! -d "ios" ]; then
            flutter create --platforms ios .
          fi

      # 4. Установка зависимостей (с принудительным обновлением CocoaPods)
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod repo update && pod install --repo-update && cd ..

      # 5. Сборка IPA (без подписи)
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign

      # 6. Подпись и финальная сборка IPA
      - name: Code signing
        script: |
          cd ios
          xcode-project use-profiles
          xcode-project build-ipa --workspace Runner.xcworkspace --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - tm6104440@gmail.com