workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch dependencies
        script: |
          flutter packages pub get
          cd ios && pod install && cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
      - name: Code signing
        script: |
          cd ios
          xcode-project use-profiles
          xcode-project build-ipa --workspace Runner.xcworkspace --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your.email@example.com