workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: "3.32.8" # Соответствует Dart 3.8.1
      xcode: latest
      cocoapods: "1.15.2"
    scripts:
      - name: Проверка окружения
        script: |
          flutter --version
          dart --version
          pod --version

      - name: Очистка проекта
        script: |
          flutter clean
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec

      - name: Создание iOS-структуры
        script: |
          if [ -d "ios" ]; then
            echo "Удаление старой iOS-структуры..."
            rm -rf ios
          fi
          echo "Создание новой iOS-структуры..."
          flutter create --platforms ios --org com.yourdomain . || {
            echo "=== ОШИБКА СОЗДАНИЯ iOS ==="
            ls -la ios/
            flutter doctor -v
            exit 1
          }

      - name: Обновление зависимостей
        script: |
          echo "Обновление Dart-пакетов..."
          flutter pub upgrade --major-versions
          
          echo "Обновление iOS-зависимостей..."
          cd ios
          pod repo update
          pod install --repo-update --verbose || {
            echo "=== ОШИБКА POD INSTALL ==="
            pod env
            ls -la
            exit 1
          }

      - name: Сборка IPA
        script: |
          flutter build ipa --release --verbose
          
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your.email@example.com