workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: "3.32.8"
      xcode: latest
      cocoapods: "1.15.2"
    scripts:
      - name: Проверка pubspec.yaml
        script: |
          if grep -q "flutter_lints:" pubspec.yaml && grep -A1 "dev_dependencies:" pubspec.yaml | grep -q "flutter_lints:"; then
            echo "Обнаружено дублирование flutter_lints в pubspec.yaml"
            exit 1
          fi

      - name: Очистка проекта
        script: |
          flutter clean
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec

      - name: Создание iOS-структуры
        script: |
          if [ -f "pubspec.yaml" ]; then
            echo "Проверка pubspec.yaml..."
            if ! flutter analyze; then
              echo "Ошибка в pubspec.yaml, исправьте файл"
              exit 1
            fi
          fi
          
          if [ -d "ios" ]; then
            echo "Удаление старой iOS-структуры..."
            rm -rf ios
          fi
          
          echo "Создание новой iOS-структуры..."
          flutter create --platforms ios --org com.yourdomain .

      - name: Установка зависимостей
        script: |
          flutter pub get
          cd ios
          pod repo update
          pod install --repo-update

      - name: Сборка IPA
        script: |
          flutter build ipa --release --verbose
          
    artifacts:
      - build/ios/ipa/*.ipa